GET http://localhost:3947/challenge
###

POST http://localhost:3947/verify
Content-Type: application/json

{
"payload": "eyJhbGdvcml0aG0iOiJTSEEtMjU2IiwiY2hhbGxlbmdlIjoiN2U5MTUxM2ViZGJjYmVjMjdhYTkxOWM5ZTE0MzE0N2U4NzcxNWYzOTAxZDRkNGM5Njk1NDg2YWFmNzJkMzViOCIsIm51bWJlciI6OTAzMzA3LCJzYWx0IjoiMmUzNDFlNDkxOGU2OWE3MWQyZWFkYWM1P2V4cGlyZXM9MTc3MjgxOTE0OSYiLCJzaWduYXR1cmUiOiJiMmVmZmExYTRhNTU1ZjEzNThhMWNmMDIwZjdiMWRjMTRiOTk2YTg4YWU2NjUwM2IwZjg5YmFjZjlhMWY3YTNiIiwidG9vayI6Nzk2fQ=="
}